-- Схема базы данных учебного проекта ProjectSpace
create extension if not exists "pgcrypto";

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '', phone text default '', about text default '',
  role text not null default 'user' check (role in ('user', 'admin')),
  is_blocked boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.projects (
  id uuid primary key default gen_random_uuid(), name text not null,
  description text default '',
  status text not null default 'active' check (status in ('active', 'completed', 'paused')),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  start_date date, end_date date, created_at timestamptz not null default now()
);

create table public.project_members (
  project_id uuid references public.projects(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  member_role text not null default 'member' check (member_role in ('owner', 'member')),
  primary key (project_id, user_id)
);

create table public.tasks (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  title text not null, description text default '',
  status text not null default 'new' check (status in ('new', 'in_progress', 'done')),
  priority text not null default 'medium' check (priority in ('low', 'medium', 'high')),
  assignee_id uuid references public.profiles(id) on delete set null,
  creator_id uuid not null references public.profiles(id) on delete cascade,
  due_date date, created_at timestamptz not null default now()
);

create table public.comments (
  id uuid primary key default gen_random_uuid(), task_id uuid not null references public.tasks(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  content text not null, created_at timestamptz not null default now()
);

create table public.notifications (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade,
  message text not null, link text default '', is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.activity_logs (
  id bigint generated by default as identity primary key,
  project_id uuid references public.projects(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete set null,
  action text not null, created_at timestamptz not null default now()
);

create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id, full_name) values (new.id, coalesce(new.raw_user_meta_data->>'full_name', ''));
  return new;
end; $$;
create trigger create_profile_after_signup after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.add_project_owner() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.project_members(project_id, user_id, member_role) values (new.id, new.owner_id, 'owner');
  return new;
end; $$;
create trigger add_owner_after_project after insert on public.projects
for each row execute function public.add_project_owner();

create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists(select 1 from profiles where id = auth.uid() and role = 'admin' and not is_blocked);
$$;
create or replace function public.is_active_user() returns boolean
language sql stable security definer set search_path = public as $$
  select exists(select 1 from profiles where id = auth.uid() and not is_blocked);
$$;
create or replace function public.is_project_member(project uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists(select 1 from project_members where project_id = project and user_id = auth.uid());
$$;
create or replace function public.is_project_owner(project uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists(select 1 from projects where id = project and owner_id = auth.uid());
$$;

alter table profiles enable row level security;
alter table projects enable row level security;
alter table project_members enable row level security;
alter table tasks enable row level security;
alter table comments enable row level security;
alter table notifications enable row level security;
alter table activity_logs enable row level security;

create policy "profiles available to users" on profiles for select to authenticated using (is_active_user() or is_admin());
create policy "user edits profile" on profiles for update to authenticated using (id = auth.uid() or is_admin()) with check (id = auth.uid() or is_admin());
create policy "projects read by members" on projects for select to authenticated using (is_active_user() and (is_project_member(id) or owner_id = auth.uid() or is_admin()));
create policy "users create projects" on projects for insert to authenticated with check (is_active_user() and owner_id = auth.uid());
create policy "owners edit projects" on projects for update to authenticated using (is_project_owner(id) or is_admin()) with check (is_project_owner(id) or is_admin());
create policy "owners delete projects" on projects for delete to authenticated using (is_project_owner(id) or is_admin());
create policy "members list team" on project_members for select to authenticated using (is_project_member(project_id) or is_project_owner(project_id) or is_admin());
create policy "owners add team" on project_members for insert to authenticated with check (is_project_owner(project_id) or is_admin());
create policy "owners remove team" on project_members for delete to authenticated using (is_project_owner(project_id) or is_admin());
create policy "members read tasks" on tasks for select to authenticated using (is_active_user() and (is_project_member(project_id) or is_admin()));
create policy "members create tasks" on tasks for insert to authenticated with check (is_active_user() and is_project_member(project_id) and creator_id = auth.uid());
create policy "members edit tasks" on tasks for update to authenticated using (is_project_member(project_id) or is_admin()) with check (is_project_member(project_id) or is_admin());
create policy "members delete tasks" on tasks for delete to authenticated using (is_project_member(project_id) or is_admin());
create policy "members read comments" on comments for select to authenticated using (exists(select 1 from tasks t where t.id = task_id and is_project_member(t.project_id)) or is_admin());
create policy "members create comments" on comments for insert to authenticated with check (author_id = auth.uid() and exists(select 1 from tasks t where t.id = task_id and is_project_member(t.project_id)));
create policy "authors delete comments" on comments for delete to authenticated using (author_id = auth.uid() or is_admin());
create policy "users read notifications" on notifications for select to authenticated using (user_id = auth.uid() or is_admin());
create policy "users update notifications" on notifications for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "users create notifications" on notifications for insert to authenticated with check (is_active_user());
create policy "members read activity" on activity_logs for select to authenticated using (is_project_member(project_id) or is_admin());
create policy "users create activity" on activity_logs for insert to authenticated with check (user_id = auth.uid() and is_project_member(project_id));

create index tasks_project_id_index on tasks(project_id);
create index tasks_assignee_id_index on tasks(assignee_id);
create index comments_task_id_index on comments(task_id);
create index notifications_user_id_index on notifications(user_id);

-- Обычный пользователь может менять только безопасные поля своего профиля.
revoke update on public.profiles from authenticated;
grant update(full_name, phone, about) on public.profiles to authenticated;

create or replace function public.admin_update_user(target_id uuid, new_role text, blocked boolean)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'Недостаточно прав'; end if;
  if new_role not in ('user', 'admin') then raise exception 'Неизвестная роль'; end if;
  update profiles set role = new_role, is_blocked = blocked where id = target_id;
end; $$;
grant execute on function public.admin_update_user(uuid, text, boolean) to authenticated;

-- После регистрации администратора выполнить один раз, подставив его email:
-- update public.profiles set role = 'admin'
-- where id = (select id from auth.users where email = 'admin@example.com');
